/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWeeklyReviewRouteImport } from './routes/api/weekly-review'
import { Route as ApiVisionRouteImport } from './routes/api/vision'
import { Route as ApiCoachRouteImport } from './routes/api/coach'
import { Route as AppWellnessRouteImport } from './routes/_app/wellness'
import { Route as AppWeeklyRouteImport } from './routes/_app/weekly'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppPeriodRouteImport } from './routes/_app/period'
import { Route as AppNutritionRouteImport } from './routes/_app/nutrition'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCoachRouteImport } from './routes/_app/coach'
import { Route as AppAchievementsRouteImport } from './routes/_app/achievements'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeeklyReviewRoute = ApiWeeklyReviewRouteImport.update({
  id: '/api/weekly-review',
  path: '/api/weekly-review',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisionRoute = ApiVisionRouteImport.update({
  id: '/api/vision',
  path: '/api/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoachRoute = ApiCoachRouteImport.update({
  id: '/api/coach',
  path: '/api/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWellnessRoute = AppWellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => AppRoute,
} as any)
const AppWeeklyRoute = AppWeeklyRouteImport.update({
  id: '/weekly',
  path: '/weekly',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPeriodRoute = AppPeriodRouteImport.update({
  id: '/period',
  path: '/period',
  getParentRoute: () => AppRoute,
} as any)
const AppNutritionRoute = AppNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AppAchievementsRoute
  '/coach': typeof AppCoachRoute
  '/dashboard': typeof AppDashboardRoute
  '/nutrition': typeof AppNutritionRoute
  '/period': typeof AppPeriodRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/weekly': typeof AppWeeklyRoute
  '/wellness': typeof AppWellnessRoute
  '/api/coach': typeof ApiCoachRoute
  '/api/vision': typeof ApiVisionRoute
  '/api/weekly-review': typeof ApiWeeklyReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AppAchievementsRoute
  '/coach': typeof AppCoachRoute
  '/dashboard': typeof AppDashboardRoute
  '/nutrition': typeof AppNutritionRoute
  '/period': typeof AppPeriodRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/weekly': typeof AppWeeklyRoute
  '/wellness': typeof AppWellnessRoute
  '/api/coach': typeof ApiCoachRoute
  '/api/vision': typeof ApiVisionRoute
  '/api/weekly-review': typeof ApiWeeklyReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/achievements': typeof AppAchievementsRoute
  '/_app/coach': typeof AppCoachRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/nutrition': typeof AppNutritionRoute
  '/_app/period': typeof AppPeriodRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/weekly': typeof AppWeeklyRoute
  '/_app/wellness': typeof AppWellnessRoute
  '/api/coach': typeof ApiCoachRoute
  '/api/vision': typeof ApiVisionRoute
  '/api/weekly-review': typeof ApiWeeklyReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/coach'
    | '/dashboard'
    | '/nutrition'
    | '/period'
    | '/reports'
    | '/settings'
    | '/weekly'
    | '/wellness'
    | '/api/coach'
    | '/api/vision'
    | '/api/weekly-review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/coach'
    | '/dashboard'
    | '/nutrition'
    | '/period'
    | '/reports'
    | '/settings'
    | '/weekly'
    | '/wellness'
    | '/api/coach'
    | '/api/vision'
    | '/api/weekly-review'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/achievements'
    | '/_app/coach'
    | '/_app/dashboard'
    | '/_app/nutrition'
    | '/_app/period'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/weekly'
    | '/_app/wellness'
    | '/api/coach'
    | '/api/vision'
    | '/api/weekly-review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiCoachRoute: typeof ApiCoachRoute
  ApiVisionRoute: typeof ApiVisionRoute
  ApiWeeklyReviewRoute: typeof ApiWeeklyReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weekly-review': {
      id: '/api/weekly-review'
      path: '/api/weekly-review'
      fullPath: '/api/weekly-review'
      preLoaderRoute: typeof ApiWeeklyReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vision': {
      id: '/api/vision'
      path: '/api/vision'
      fullPath: '/api/vision'
      preLoaderRoute: typeof ApiVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coach': {
      id: '/api/coach'
      path: '/api/coach'
      fullPath: '/api/coach'
      preLoaderRoute: typeof ApiCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/wellness': {
      id: '/_app/wellness'
      path: '/wellness'
      fullPath: '/wellness'
      preLoaderRoute: typeof AppWellnessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/weekly': {
      id: '/_app/weekly'
      path: '/weekly'
      fullPath: '/weekly'
      preLoaderRoute: typeof AppWeeklyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/period': {
      id: '/_app/period'
      path: '/period'
      fullPath: '/period'
      preLoaderRoute: typeof AppPeriodRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nutrition': {
      id: '/_app/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof AppNutritionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coach': {
      id: '/_app/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/achievements': {
      id: '/_app/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppCoachRoute: typeof AppCoachRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppNutritionRoute: typeof AppNutritionRoute
  AppPeriodRoute: typeof AppPeriodRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWeeklyRoute: typeof AppWeeklyRoute
  AppWellnessRoute: typeof AppWellnessRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppCoachRoute: AppCoachRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppNutritionRoute: AppNutritionRoute,
  AppPeriodRoute: AppPeriodRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWeeklyRoute: AppWeeklyRoute,
  AppWellnessRoute: AppWellnessRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiCoachRoute: ApiCoachRoute,
  ApiVisionRoute: ApiVisionRoute,
  ApiWeeklyReviewRoute: ApiWeeklyReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
